# Generated by Django 4.2.1 on 2023-05-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('btn_name1', models.CharField(max_length=40, verbose_name='Button Name 1')),
                ('subtitle1', models.CharField(max_length=60, verbose_name='Subtitle 1')),
                ('subtitle2', models.CharField(max_length=60, verbose_name='Subtitle 2')),
                ('subtitle3', models.CharField(max_length=60, verbose_name='Subtitle 3')),
                ('btn_name2', models.CharField(max_length=40, verbose_name='Button Name 2')),
            ],
        ),
    ]
