# Generated by Django 4.2.1 on 2023-05-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_home'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Home', 'verbose_name_plural': 'Home'},
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Title'),
        ),
    ]
