# Generated by Django 4.2.1 on 2023-05-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_homeslider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeslider',
            options={'verbose_name': 'Home Slider', 'verbose_name_plural': 'Home Slider'},
        ),
        migrations.AddField(
            model_name='homeslider',
            name='class_id',
            field=models.PositiveIntegerField(default=1, verbose_name='Dont Change This'),
            preserve_default=False,
        ),
    ]
