# Generated by Django 4.2.1 on 2023-05-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_homeslider_options_homeslider_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='general_title',
            field=models.CharField(default=1, max_length=50, verbose_name='Page Title'),
            preserve_default=False,
        ),
    ]
