# Generated by Django 4.2.1 on 2023-05-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_home_general_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='Background Image')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=80, verbose_name='Subtitle')),
                ('btn_name', models.CharField(max_length=40, verbose_name='Button Name')),
            ],
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='img',
            field=models.ImageField(upload_to='images', verbose_name='Background Image'),
        ),
    ]
