# Generated by Django 4.2.1 on 2023-05-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_dealcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='daily',
            field=models.CharField(default=1, max_length=50, verbose_name='Daily'),
            preserve_default=False,
        ),
    ]
