# Generated by Django 4.2.1 on 2023-05-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_deal_daily'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('btn_name', models.CharField(max_length=40, verbose_name='Button Name')),
                ('link_name', models.CharField(max_length=50, verbose_name='Link Name')),
                ('google_map', models.URLField(verbose_name='Google Map')),
            ],
        ),
    ]
