# Generated by Django 4.2.1 on 2023-05-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_homecontainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecontainer',
            name='google_map',
            field=models.TextField(verbose_name='Google Map'),
        ),
    ]
