# Generated by Django 4.2.1 on 2023-05-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_homecontainer_google_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealcontent',
            name='to_check',
            field=models.BooleanField(blank=True, default=1, verbose_name='To Check'),
            preserve_default=False,
        ),
    ]
