# Generated by Django 4.2.1 on 2023-05-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_dealcontent_to_check_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealcontent',
            name='to_check_slider',
        ),
        migrations.AddField(
            model_name='deal',
            name='general_title',
            field=models.CharField(default=1, max_length=50, verbose_name='Page Title'),
            preserve_default=False,
        ),
    ]
