# Generated by Django 4.2.1 on 2023-05-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_dealcontent_to_check_slider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_title', models.CharField(max_length=50, verbose_name='Page Title')),
                ('img', models.ImageField(upload_to='images', verbose_name='Background Image')),
                ('title1', models.CharField(max_length=50, verbose_name='Title 1')),
                ('subtitle', models.CharField(max_length=60, verbose_name='Subtitle')),
                ('text', models.TextField(verbose_name='Text')),
                ('btn_name', models.CharField(max_length=40, verbose_name='Button Name')),
                ('title2', models.CharField(max_length=50, verbose_name='Title 2')),
            ],
        ),
    ]
