# Generated by Django 4.2.1 on 2023-05-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_about_img_about_img1_about_img2'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title2_colored',
            field=models.CharField(default=1, max_length=50, verbose_name='Title 2 Colored'),
            preserve_default=False,
        ),
    ]
