# Generated by Django 4.2.1 on 2023-05-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_aboutpricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPricingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='Image')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('people', models.CharField(max_length=50, verbose_name='People')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('count', models.CharField(max_length=30, verbose_name='Person Count')),
                ('offer1', models.CharField(max_length=60, verbose_name='Offer 1')),
                ('offer2', models.CharField(max_length=60, verbose_name='Offer 2')),
                ('offer3', models.CharField(max_length=60, verbose_name='Offer 3')),
            ],
        ),
        migrations.AlterModelOptions(
            name='aboutpricing',
            options={'verbose_name': 'About Pricing', 'verbose_name_plural': 'About Pricing'},
        ),
    ]
