# Generated by Django 4.2.1 on 2023-05-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_aboutpricingcontent_alter_aboutpricing_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='Image')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('text1', models.TextField(verbose_name='Text 1')),
                ('subtitle1', models.CharField(max_length=60, verbose_name='Subtitle 1')),
                ('info1', models.CharField(max_length=30, verbose_name='Info 1')),
                ('subtitle2', models.CharField(max_length=60, verbose_name='Subtitle 2')),
                ('info2', models.CharField(max_length=30, verbose_name='Info 2')),
                ('subtitle3', models.CharField(max_length=60, verbose_name='Subtitle 3')),
                ('info3', models.CharField(max_length=30, verbose_name='Info 3')),
                ('subtitle4', models.CharField(max_length=60, verbose_name='Subtitle 4')),
                ('info4', models.CharField(max_length=30, verbose_name='Info 4')),
                ('text2', models.TextField(verbose_name='Text 2')),
                ('btn_name', models.CharField(max_length=40, verbose_name='Button Name')),
            ],
        ),
    ]
