# Generated by Django 4.2.1 on 2023-05-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('info', models.CharField(max_length=60, verbose_name='Info 1')),
            ],
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservation'},
        ),
    ]
