# Generated by Django 4.2.1 on 2023-05-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_reservationcontent_alter_reservation_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationGet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_map', models.TextField(verbose_name='Google Map')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('colored_title', models.CharField(max_length=50, verbose_name='Colored Title')),
                ('placeholder1', models.CharField(max_length=50, verbose_name='Placeholder 1')),
                ('placeholder2', models.CharField(max_length=50, verbose_name='Placeholder 2')),
                ('placeholder3', models.CharField(max_length=50, verbose_name='Placeholder 3')),
                ('placeholder4', models.CharField(max_length=50, verbose_name='Placeholder 4')),
                ('placeholder5', models.CharField(max_length=50, verbose_name='Placeholder 5')),
                ('btn_name', models.CharField(max_length=40, verbose_name='Button Name')),
            ],
        ),
    ]
