# Generated by Django 4.2.1 on 2023-05-27 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_reservationget'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationget',
            options={'verbose_name': 'Reservation GET', 'verbose_name_plural': 'Reservation GET'},
        ),
    ]
