# Generated by Django 4.2.1 on 2023-05-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_reservationget_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='Username')),
                ('user_phone', models.CharField(max_length=50, verbose_name='User Phone Number')),
                ('user_count', models.CharField(max_length=10, verbose_name='User Count')),
                ('user_date', models.CharField(max_length=10, verbose_name='User Date')),
                ('user_destination', models.CharField(max_length=50, verbose_name='User Destination')),
            ],
            options={
                'verbose_name': 'Reservation POST',
                'verbose_name_plural': 'Reservation POST',
            },
        ),
    ]
