# Generated by Django 4.2.1 on 2023-05-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_reservationpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=80, verbose_name='Subtitle')),
                ('btn_name', models.CharField(max_length=40, verbose_name='Button Name')),
            ],
        ),
    ]
