# Generated by Django 4.2.1 on 2023-05-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_reservationoffer_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright1', models.CharField(max_length=150, verbose_name='Copyright')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('name_link', models.URLField(verbose_name='Name Link')),
            ],
        ),
    ]
